list/urls.py
from django.urls import path
from . import views

app_name = 'list'
urlpatterns = [
    path('<slug:list_name>/', views.ItemListView.as_view(), name='list_items'),
    path('<slug:list_name>/<int:pk>/', views.ShowItemView.as_view(),
         name='show_item'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('staff/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(
        template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('schedule/', include('schedule.urls')),
    path('', include('welcome.urls')),
    path('list/', include('list.urls')),
    path('contacts/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schedule/urls.py
from django.urls import path
from . import views

app_name = 'schedule'
urlpatterns = [
    path('', views.ScheduleView.as_view(), name='schedule'),
]

list/models.py
from django.db import models

# Create your models here.

list/views.py
import pdb

from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import Http404
from django.forms.models import model_to_dict

from schedule.models import Teachers, Subjects

def to_model(key:str):
    """Return model from str typed key.
    
    A very strict name string to model converter that only allows
    specific model names defined in 'models' local var.
    """
    models = {
        'teachers': Teachers,
        'classes': Subjects,
    }
    if key not in models:
        raise Http404
    
    return models[key]

def object_list_to_dict_list(obj_list:list, spec=False):
    """Return dict of a Django orm model object.
    
    A wrapper over model_to_dict() to do it for a large number of 
    objects.
    """
    result = []
    for elem in obj_list:
        result.append(model_to_dict(elem))
        if spec:
            result[-1]['speciality_active'] = \
                                            elem.speciality.filter(active=True)
    
    return result

# Create your views here.
class ItemListView(generic.ListView):
    """Return model object list context depending on request param."""
    template_name = "list/item_list.html"
    paginate_by = 6
    ordering = ['-importance', 'name']

    def get_queryset(self, **kwargs):
        self.model = to_model(self.kwargs['list_name'])
        
        return super().get_queryset(**kwargs).filter(active=True)

    def get_context_data(self, **kwargs):
        spec = False
        context = super().get_context_data(**kwargs)
        if self.kwargs['list_name'] == 'teachers':
            spec = True  # this is needed to poroperly treat m-2-m feild filter
                         # in object_list_to_dict_list as a quickfix
        context['object_list'] = \
                         object_list_to_dict_list(context['object_list'], spec)
        context['table'] = self.kwargs['list_name']
        
        return context
    

class ShowItemView(generic.DetailView):
    """Return a model object context depending on request param."""
    template_name = "list/show_item.html"

    def get_queryset(self, **kwargs):
        self.model = to_model(self.kwargs['list_name'])
        
        return super().get_queryset(**kwargs).filter(active=True)
    
    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        if self.kwargs['list_name'] == 'teachers':
            context['speciality_active'] = \
                               context['object'].speciality.filter(active=True)
        context['table'] = self.kwargs['list_name']
        
        return context

list/templates/list/item_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Welcome to Fantasy School{% endblock title %}

{% block styles %}
{% load static %} <link rel="stylesheet" type="text/css" href="{% static 'list/styles.css' %}">
{% endblock styles %}

{% block scripts %} 
<script type="text/javascript" src="{% static 'list/listeners.js' %}" defer></script> 
{% endblock scripts %}

{% block topbar-menu-teachers %}
	{% if table == 'teachers' %}
	<a href="{% url 'list:list_items' list_name='teachers' %}">
		<div class="topbar-menu-current col-auto color-red-on-hover">Teachers</div>
	</a>
	{% else %}
	<a href="{% url 'list:list_items' list_name='teachers' %}">
		<div class="col-auto color-red-on-hover">Teachers</div>
	</a>
	{% endif %}
{% endblock topbar-menu-teachers %}
{% block topbar-menu-classes %}
	{% if table == 'classes' %}
	<a href="{% url 'list:list_items' list_name='classes' %}">
		<div class="topbar-menu-current col-auto color-red-on-hover">Classes</div>
	</a>
	{% else %}
	<a href="{% url 'list:list_items' list_name='classes' %}">
		<div class="col-auto color-red-on-hover">Classes</div>
	</a>
	{% endif %}
{% endblock topbar-menu-classes %}

{% block page-content %}
<div class="content container">
	
	<div class="row items-row">
		{% for item in object_list %}
		<a class="col-4 item-container-container color-text-over-overlay h-100" href="{% url 'list:show_item' list_name=table pk=item.id %}">
			<div class="covered item-container h-100">
				{% if item.photo_small %}
				<div class="item-img cover-parent" style="background-image: url('{{ item.photo_small.url }}')">
				{% else %}
				<div class="item-img cover-parent" style="background-color: rgb(150, 150, 150)">
				{% endif %}
					<div class="overlay color-red-filled h-100 w-100"></div>
				</div>
				<div class="item-name-container">
					<h1 class="item-name-box">{{ item.name }}</h1>
				</div>
				<div class="item-descrption-container">
					{% if item.speciality_active %}
					<p class="item-descrption-box">
					{% for class in item.speciality_active %} 
					{{ class }}{% if not forloop.last %}, {% endif %}
					{% endfor %}
					</p>
					{% endif %}
				</div>
			</div>
		</a>
		{% empty %}
		<p>No entiries found!</p>
		{% endfor %}
	</div>
	
	
	{% if is_paginated %}
       <div class="pagination row">
		<div class="col text-center">
			{% if page_obj.has_previous %}
			<a class="paginator-arrows colors-main-text" href="{% url 'list:list_items' list_name=table %}?page={{ page_obj.previous_page_number }}">
				<span class="center-text paginator-arrows-icon">&lt</span>
			</a>
			{% else %}
			<div class="paginator-arrows-disabled">
				<span class="center-text paginator-arrows-icon">&lt</span>
			</div>
			{% endif %}
		</div>
		<div class="col text-center paginator-pages">
			<div class="row justify-content-center">
				{% spaceless %}
				{% with ' '|center:page_obj.paginator.num_pages as range %}
				{% for _ in range %}
				{% if forloop.counter == page_obj.number %}
				<div class="col-1 text-center"><div class="paginator-page-repr paginator-page-repr-current"></div></div>
				{% else %}
				<div class="col-1 text-center"><div class="paginator-page-repr"></div></div>
				{% endif %}
				{% endfor %}
				{% endwith %}
				{% endspaceless %}
			</div>
		</div>
		<div class="col text-center">
			{% if page_obj.has_next %}
			<a class="paginator-arrows colors-main-text" href="{% url 'list:list_items' list_name=table %}?page={{ page_obj.next_page_number }}">
				<span class="center-text paginator-arrows-icon">&gt</span>
			</a>
			{% else %}
			<div class="paginator-arrows-disabled">
				<span class="center-text paginator-arrows-icon">&gt</span>
			</div>
			{% endif %}
		</div>
	</div>
	{% endif %}
</div>
{% endblock page-content %}

list/templates/list/show_item.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Welcome to Fantasy School{% endblock title %}

{% block styles %}
{% load static %} <link rel="stylesheet" type="text/css" href="{% static 'list/styles.css' %}">
{% endblock styles %}

{% block topbar-menu-teachers %}
	{% if table == 'teachers' %}
	<a href="{% url 'list:list_items' list_name='teachers' %}">
		<div class="topbar-menu-current col-auto color-red-on-hover">Teachers</div>
	</a>
	{% else %}
	<a href="{% url 'list:list_items' list_name='teachers' %}">
		<div class="col-auto color-red-on-hover">Teachers</div>
	</a>
	{% endif %}
{% endblock topbar-menu-teachers %}
{% block topbar-menu-classes %}
	{% if table == 'classes' %}
	<a href="{% url 'list:list_items' list_name='classes' %}">
		<div class="topbar-menu-current col-auto color-red-on-hover">Classes</div>
	</a>
	{% else %}
	<a href="{% url 'list:list_items' list_name='classes' %}">
		<div class="col-auto color-red-on-hover">Classes</div>
	</a>
	{% endif %}
{% endblock topbar-menu-classes %}

{% block page-content %}
	<div class="content container">
		
			<div class="row detail-item-container">
				<div class="col-3 detail-avatar-container">
					{% if object.photo_small %}
					<img class="row detail-avatar-img" src="{{ object.photo_small.url }}">
					{% else %}
					<img class="row detail-avatar-img" src="">
					{% endif %}
					{% if table == 'teachers' %}<a href="{% url 'schedule:schedule' %}?teacher={{ object.name }}" class="row">Click here to see classes by {{ object.name }}</a>
					{%  elif table == 'classes' %}<a href="{% url 'schedule:schedule' %}?subj={{ object.name }}" class="row">Click here to see  {{ object.name }} classes</a>
					{% endif %}
				</div>
				<div class="col-auto detail-item-text-box colors-main-text">
					<div class="row">
						<h4 id="detail-item-name">{{ object.name }}</h4>
					</div>
					{% if speciality_active %}
					<div class="row detail-item-text-box-text">
						<p>Speciality: 
						{% for class in speciality_active %} 
						{{ class }}{% if not forloop.last %}, {% endif %}
						{% endfor %}
						</p>
					</div>
					{% endif %}
					<div class="row">
						<p class="detail-item-text-box-text">{{ object.description }}</p>
					</div>
				</div>
			</div>
		
	</div>
{% endblock page-content %}